version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
      image: dpage/pgadmin4
      restart: always
      container_name: nest-pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - '5050:80'
      depends_on:
        - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-typeORM
    environment:
      - APP_PORT=${APP_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_TYPE=${DB_TYPE}
      - DB_USER=${DB_USER}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
